---
- name: Install Ruby
  apt: pkg=ruby update-cache=yes
  sudo: yes
  tags: ruby

- name: Install git
  apt: pkg=git update-cache=yes
  sudo: yes
  tags: git

- name: Create .gitconfig with default user.name and user.email.
  sudo: no
  template: src=.gitconfig.j2 dest=/home/vagrant/.gitconfig force=no
  tags: git

- name: Install libpng-dev
  apt: pkg=libpng-dev update-cache=yes
  sudo: yes
  tags: libpng-dev

- name: Install libfontconfig-dev
  apt: pkg=libfontconfig-dev update-cache=yes
  sudo: yes
  tags: libfontconfig-dev

- name: Install build-essential
  apt: pkg=build-essential update-cache=yes
  sudo: yes
  tags: build-essential

- name: Install heroku-toolbelt
  include: 'heroku.yml'
  sudo: yes
  tags: heroku-toolbelt

- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*db$' line="192.168.111.223 db" state=present
  tags: etc/hosts

- name: Install nodejs, npm, and npm packages
  include: node.yml
  tags: nodejs

- name: Register app path
  stat: path=/vagrant/app
  register: check_path

- name: Create app dir and run yo generator if app directory is not present.
  include: app.yml
  when: check_path.stat.exists == false

- name: Start in /vagrant directory when ssh
  lineinfile: dest=/home/vagrant/.bashrc regexp='^cd /vagrant/app$' line="cd /vagrant/app" state=present
  tags: .bashrc
